services:
  mysql:
    image: mysql
    container_name: mysqlDB
    ports:
      - "3307:3307"
    expose:
      - 3307
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Am@0311865186
      MYSQL_ROOT_PASSWORD: Am@0311865186
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - saga

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - saga

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - saga

  eureka:
    build: Eureka
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - saga
    deploy:
      resources:
        limits:
          memory: 512m

  gateway:
    build: Gateway
    container_name: gateway
    ports:
      - "7070:7070"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on: [ eureka ]
    networks:
      - saga
    deploy:
      resources:
        limits:
          memory: 512m

  deposit:
    build: deposit
    ports:
      - "8080:8080"
    container_name: deposit
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - saga
    depends_on: [ mysql, eureka ]
    deploy:
      resources:
        limits:
          memory: 512m

  withdraw:
    build: withdraw
    ports:
      - "8082:8082"
    container_name: withdraw
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - saga
    depends_on: [ mysql, eureka ]
    deploy:
      resources:
        limits:
          memory: 512m
networks:
  default:
  saga:
    driver: bridge